# Generated by Django 4.2.30 on 2026-05-29 04:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("db", "0121_alter_estimate_type"),
    ]

    operations = [
        migrations.CreateModel(
            name="AuthenticationAuditLog",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Last Modified At"
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Deleted At"
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("SIGN_IN", "Sign in"),
                            ("SIGN_UP", "Sign up"),
                            ("SIGN_OUT", "Sign out"),
                            ("SIGN_IN_FAILED", "Sign in failed"),
                        ],
                        db_index=True,
                        max_length=32,
                    ),
                ),
                ("email", models.CharField(blank=True, max_length=255, null=True)),
                ("medium", models.CharField(blank=True, max_length=32, null=True)),
                ("origin", models.CharField(blank=True, max_length=16, null=True)),
                ("error_code", models.CharField(blank=True, max_length=64, null=True)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.CharField(blank=True, max_length=512, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created_by",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created By",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated_by",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Last Modified By",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="auth_audit_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Authentication Audit Log",
                "verbose_name_plural": "Authentication Audit Logs",
                "db_table": "authentication_audit_logs",
                "ordering": ("-created_at",),
                "indexes": [
                    models.Index(
                        fields=["event_type", "-created_at"],
                        name="authenticat_event_t_647112_idx",
                    ),
                    models.Index(
                        fields=["user", "-created_at"],
                        name="authenticat_user_id_aba6b7_idx",
                    ),
                ],
            },
        ),
    ]
