# Generated by Django 4.2.30 on 2026-06-14 12:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("db", "0122_authenticationauditlog"),
    ]

    operations = [
        migrations.CreateModel(
            name="AccessAuditLog",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Last Modified At"
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Deleted At"
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("MEMBER_ADDED", "Member added"),
                            ("MEMBER_REMOVED", "Member removed"),
                            ("ROLE_CHANGED", "Role changed"),
                        ],
                        db_index=True,
                        max_length=32,
                    ),
                ),
                (
                    "scope",
                    models.CharField(
                        choices=[("WORKSPACE", "Workspace"), ("PROJECT", "Project")],
                        max_length=16,
                    ),
                ),
                (
                    "target_email",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "previous_role",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                ("new_role", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.CharField(blank=True, max_length=512, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created_by",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created By",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="access_audit_logs",
                        to="db.project",
                    ),
                ),
                (
                    "target_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="access_audit_target_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated_by",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Last Modified By",
                    ),
                ),
                (
                    "workspace",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="access_audit_logs",
                        to="db.workspace",
                    ),
                ),
            ],
            options={
                "verbose_name": "Access Audit Log",
                "verbose_name_plural": "Access Audit Logs",
                "db_table": "access_audit_logs",
                "ordering": ("-created_at",),
                "indexes": [
                    models.Index(
                        fields=["event_type", "-created_at"],
                        name="access_audi_event_t_7a417e_idx",
                    ),
                    models.Index(
                        fields=["workspace", "-created_at"],
                        name="access_audi_workspa_35c268_idx",
                    ),
                    models.Index(
                        fields=["target_user", "-created_at"],
                        name="access_audi_target__b3777c_idx",
                    ),
                ],
            },
        ),
    ]
