# Generated by Django 4.2.30 on 2026-06-22 23:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("db", "0123_accessauditlog"),
    ]

    operations = [
        migrations.CreateModel(
            name="DataExportAuditLog",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Last Modified At"
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Deleted At"
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                (
                    "export_type",
                    models.CharField(
                        choices=[
                            ("ISSUES", "Issues export"),
                            ("ANALYTICS", "Analytics export"),
                        ],
                        db_index=True,
                        max_length=32,
                    ),
                ),
                ("provider", models.CharField(blank=True, max_length=32, null=True)),
                ("project_count", models.PositiveIntegerField(blank=True, null=True)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.CharField(blank=True, max_length=512, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created_by",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created By",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated_by",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Last Modified By",
                    ),
                ),
                (
                    "workspace",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="data_export_audit_logs",
                        to="db.workspace",
                    ),
                ),
            ],
            options={
                "verbose_name": "Data Export Audit Log",
                "verbose_name_plural": "Data Export Audit Logs",
                "db_table": "data_export_audit_logs",
                "ordering": ("-created_at",),
                "indexes": [
                    models.Index(
                        fields=["export_type", "-created_at"],
                        name="data_export_export__8c5158_idx",
                    ),
                    models.Index(
                        fields=["workspace", "-created_at"],
                        name="data_export_workspa_ca011b_idx",
                    ),
                ],
            },
        ),
    ]
